### ISSUE TITLE
Add dynamic row creation behavior

### ISSUE THREAD

**Issue by josecolella** [JacobPotter/Tracker#2]
- Add the functionality to add new rows dynamically

**Comment by JacobPotter** [comment]
I like this library Jose. Posting link here for Dan too https://vuejs.org/v2/guide/

**Comment by josecolella** [comment]
@JacobPotter Behavior has been added with the following commit https://github.com/josecolella/Tracker/commit/720aa4d7dcbf1e2b937f883e3040e71ce081cffe

**Comment by Dynatrace-Daniel-Pohanka** [comment]
subtotal calculation is no longer working

**Comment by josecolella** [comment]
Only dynamic row feature has been added . I'll be adding deletion of elements and calculations next

**Comment by josecolella** [comment]
A pull request will be done when the functionality that is present has been implemented

**Comment by JacobPotter** [comment]
Jose has fixed this
